#!/usr/bin/env python3
"""Backfill HK grocery price history from Consumer Council Online Price Watch.

Six modes, stdlib only:
  --fetch --start YYYY-MM-DD   download missing daily CSV snapshots into raw/
                                (resumable, cache-skip; local/rare — recent
                                raw/ CSVs are plain git, older years live as
                                tar bundles on the GitHub Release
                                `raw-archive` and must be restored first).
  --rebuild                    regenerate products.json from every CSV
                                already cached in raw/ (local/rare, needs the
                                full CSV history restored).
  --update                     CI daily: fetch only the days since the last
                                processed date and merge them into
                                products.json. Never trusts a locally-cached
                                raw/*.csv — always re-fetches over the
                                network for the days it processes. Exits 0
                                even on fetch failure so the site stays
                                deployable.
  --export-site DIR            regenerate products/<code>.json + index.json
                                (deploy-time site artifacts) from
                                products.json into DIR. Run by CI into dist/
                                before the Pages upload; neither
                                products/*.json nor index.json is committed.
                                Also copies names_tc.json into DIR if present.
  --build-names-tc              one-time (local/rare): sample the Traditional
                                Chinese archive CSV to build names_tc.json
                                (TC name/brand/category per product code).
                                Starts monthly-sampled, auto-densifies to
                                weekly if coverage of products.json codes
                                is under 98%.
  --build-images                one-time (local/rare): scrape one product
                                photo path per code from OPW's product pages
                                into images.json. Resumable (skips codes
                                already present, writes incrementally). Kept
                                fresh for live products by --update.

Storage:
  products.json          single committed state file — sparse per-store
                          price series plus last_seen per product, keyed by
                          product code.
  names_tc.json           committed — TC name/brand/category per product
                          code, built once by --build-names-tc and kept
                          fresh by --update. Powers the site's EN/繁 toggle.
  images.json             committed — flat {code: photo_path} built once by
                          --build-images and topped up by --update for live
                          products missing a photo. Powers product images.
  products/, index.json  generated by --export-site, never committed
                          (gitignored); index.json holds search/badge/drop
                          summaries built from products.json.
  raw/                    recent daily CSV snapshots as plain git blobs;
                          older years are rolled up into `raw-YYYY.tar.zst`
                          assets on the GitHub Release `raw-archive` to keep
                          the repo small.
"""
from __future__ import annotations

import argparse
import csv
import io
import json
import os
import re
import statistics
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import date, timedelta
from pathlib import Path

RESOURCE_URL = "https://online-price-watch.consumer.org.hk/opw/opendata/pricewatch_en.csv"
RESOURCE_URL_TC = "https://online-price-watch.consumer.org.hk/opw/opendata/pricewatch_zh-Hant.csv"
LIST_VERSIONS_URL = "https://api.data.gov.hk/v1/historical-archive/list-file-versions"
GET_FILE_URL = "https://api.data.gov.hk/v1/historical-archive/get-file"
PRODUCT_PAGE_URL = "https://online-price-watch.consumer.org.hk/opw/product/{code}"
BROWSER_USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0 Safari/537.36"
)
ROOT = Path(__file__).parent
RAW_DIR = ROOT / "raw"
STATE_JSON = ROOT / "products.json"
NAMES_TC_JSON = ROOT / "names_tc.json"
IMAGES_JSON = ROOT / "images.json"
SLEEP_SECS = 0.3
WINDOW_DAYS = 90  # for "biggest drop" / "fake discount" badges
NAMES_TC_START = date(2020, 5, 30)
NAMES_TC_COVERAGE_TARGET = 0.98

# One photo link per store per product page, e.g.
# '/opw/photoRedirect/P000000192/WELLCOME/12' -> captures ('WELLCOME', '12').
PHOTO_REDIRECT_RE = re.compile(r"/opw/photoRedirect/\w+/([A-Za-z]+)/(\d+)")
# PARKNSHOP last: its CDN is Akamai-fussy about hotlinking.
IMAGE_STORE_PREFERENCE = [
    "WELLCOME", "JASONS", "AEON", "MANNINGS", "WATSONS",
    "DCHFOOD", "LUNGFUNG", "SASA", "PARKNSHOP",
]
IMAGES_WORKERS = 1  # ponytail: OPW 403-blocks bursty/concurrent traffic
IMAGES_REQUEST_SLEEP = 1.5
IMAGES_SAVE_EVERY = 100
IMAGES_UPDATE_CAP = 150  # per --update run; ponytail: full fill takes ~2 weeks of daily runs
NO_PHOTO_KEY = "_no_photo"  # images.json reserved key: {code: last-checked ISO date}
NO_PHOTO_RECHECK_DAYS = 7

# Pre-2020-07-29 snapshots use a wide schema: one Price/Offers column pair
# per store instead of long-format Supermarket Code/Price rows. Maps the
# wide column suffix to the store code used in the long format.
WIDE_STORE_COLUMNS = {
    "Wellcome": "WELLCOME",
    "PARKnSHOP": "PARKNSHOP",
    "Market Place by Jasons": "JASONS",
    "Watsons": "WATSONS",
    "AEON": "AEON",
    "DCH Food Mart": "DCHFOOD",
}


def fetch_url(url: str, timeout: int = 30, user_agent: str = "hk-grocery-price-history/0.2") -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": user_agent})
    with urllib.request.urlopen(req, timeout=timeout) as resp:  # follows redirects
        return resp.read()


def parse_csv_bytes(raw: bytes) -> list[dict]:
    """Parse OPW CSV bytes -> list of raw row dicts (uses csv module, not
    naive split, since fields like product names can contain commas)."""
    text = raw.decode("utf-8-sig")
    return list(csv.DictReader(io.StringIO(text)))


def is_valid_snapshot(rows: list[dict]) -> bool:
    """Guard against caching a 200 response that isn't really the CSV (error
    page, empty body, schema drift) — forever, since a cached raw file is
    never re-fetched by --fetch/--rebuild."""
    if len(rows) < 100:
        return False
    header = rows[0].keys()
    if "Product Code" not in header:
        return False
    return "Price" in header or any(k.startswith("Price (") for k in header)


def to_price(raw: str) -> float | None:
    try:
        return float(raw)
    except ValueError:
        return None


def normalize_rows(raw_rows: list[dict]) -> list[dict]:
    """Raw csv.DictReader rows (either schema) -> flat rows:
    {code, brand, name, category, store, price, offer}."""
    if not raw_rows:
        return []
    header = raw_rows[0].keys()
    normalized: list[dict] = []
    if "Supermarket Code" in header:
        for row in raw_rows:
            code = row.get("Product Code")
            price = to_price(row.get("Price", ""))
            if not code or price is None:
                continue
            category = [
                p for p in (row.get("Category 1"), row.get("Category 2"), row.get("Category 3")) if p
            ]
            normalized.append({
                "code": code,
                "brand": row.get("Brand", ""),
                "name": row.get("Product Name", ""),
                "category": category,
                "store": row.get("Supermarket Code", ""),
                "price": price,
                "offer": (row.get("Offers") or "").strip() or None,
            })
    else:
        for row in raw_rows:
            code = row.get("Product Code")
            if not code:
                continue
            category = [
                p for p in (row.get("Category 1"), row.get("Category 2"), row.get("Category 3")) if p
            ]
            for col_name, store_code in WIDE_STORE_COLUMNS.items():
                price = to_price(row.get(f"Price ({col_name})", ""))
                if price is None:
                    continue
                normalized.append({
                    "code": code,
                    "brand": row.get("Brand", ""),
                    "name": row.get("Product Name", ""),
                    "category": category,
                    "store": store_code,
                    "price": price,
                    "offer": (row.get(f"Offers ({col_name})") or "").strip() or None,
                })
    return normalized


def extract_names_tc(raw: bytes) -> dict[str, dict]:
    """TC CSV bytes -> {code: {name, brand, cat}}. TC columns (貨品編號 etc.)
    are shared across the wide/long schema split, so no schema branching is
    needed here — unlike normalize_rows, which only cares about EN price
    columns that do differ between the two schemas."""
    rows = parse_csv_bytes(raw)
    out: dict[str, dict] = {}
    for row in rows:
        code = row.get("貨品編號")
        if not code:
            continue
        cat = [c for c in (row.get("貨品分類1"), row.get("貨品分類2"), row.get("貨品分類3")) if c]
        out[code] = {"name": row.get("貨品名稱", ""), "brand": row.get("品牌", ""), "cat": cat}
    return out


def list_versions(start: date, end: date, resource_url: str = RESOURCE_URL) -> list[str]:
    encoded = urllib.parse.quote(resource_url, safe="")
    url = (
        f"{LIST_VERSIONS_URL}?url={encoded}"
        f"&start={start.strftime('%Y%m%d')}&end={end.strftime('%Y%m%d')}"
    )
    body = json.loads(fetch_url(url))
    return body.get("timestamps", [])


def list_versions_chunked(start: date, end: date, resource_url: str = RESOURCE_URL) -> list[str]:
    """list-file-versions rejects windows over ~1 year; chunk the request."""
    out: list[str] = []
    cur = start
    while cur <= end:
        chunk_end = min(end, cur + timedelta(days=364))
        out.extend(list_versions(cur, chunk_end, resource_url))
        cur = chunk_end + timedelta(days=1)
    return out


def one_timestamp_per_day(timestamps: list[str]) -> dict[str, str]:
    """timestamps look like '20260601-1403'. Keep the first (earliest) per day."""
    picked: dict[str, str] = {}
    for ts in sorted(timestamps):
        day = ts.split("-")[0]
        if day not in picked:
            picked[day] = ts
    return picked


def fetch_and_cache_day(iso: str, ts: str | None, *, use_cache: bool) -> list[dict] | None:
    """Fetch one day's snapshot (ts=None means "today", live CSV), cache it
    to raw/, return normalized rows. use_cache=True reuses an existing
    raw/<iso>.csv without hitting the network (used by --fetch/--rebuild,
    which run against a full local CSV history); use_cache=False always
    re-fetches over the network (used by --update, which must never trust a
    locally-cached raw file)."""
    cache_path = RAW_DIR / f"{iso}.csv"
    if use_cache and cache_path.exists():
        return normalize_rows(parse_csv_bytes(cache_path.read_bytes()))

    url = RESOURCE_URL if ts is None else (
        f"{GET_FILE_URL}?url={urllib.parse.quote(RESOURCE_URL, safe='')}&time={ts}"
    )
    try:
        raw = fetch_url(url)
        raw_rows = parse_csv_bytes(raw)
    except (urllib.error.URLError, OSError, UnicodeDecodeError, csv.Error) as exc:
        print(f"  skip {iso}: {exc}", file=sys.stderr)
        return None

    if not is_valid_snapshot(raw_rows):
        print(f"  skip {iso}: response failed validation, not caching", file=sys.stderr)
        return None

    cache_path.write_bytes(raw)
    return normalize_rows(raw_rows)


def fetch_tc_at(ts: str | None) -> bytes | None:
    """Fetch the TC CSV at archive timestamp ts (None = today's live CSV).
    Never cached to raw/ — names_tc.json is the only artifact built from it."""
    url = RESOURCE_URL_TC if ts is None else (
        f"{GET_FILE_URL}?url={urllib.parse.quote(RESOURCE_URL_TC, safe='')}&time={ts}"
    )
    try:
        return fetch_url(url)
    except (urllib.error.URLError, OSError) as exc:
        print(f"  skip TC fetch ({ts or 'live'}): {exc}", file=sys.stderr)
        return None


def carried_forward_values(series: list[list], window_dates: list[str]) -> list[float]:
    """series: sorted [[date, price, offer], ...] (sparse: a point only on
    change). window_dates: sorted ISO dates. Returns the price effective on
    each window day (carrying the last known price forward), skipping days
    before the series' first point."""
    values: list[float] = []
    si = 0
    current: float | None = None
    n = len(series)
    for d in window_dates:
        while si < n and series[si][0] <= d:
            current = series[si][1]
            si += 1
        if current is not None:
            values.append(current)
    return values


def build_index(state: dict) -> dict:
    products = state["products"]
    today = date.today()
    window_dates = [(today - timedelta(days=i)).isoformat() for i in range(WINDOW_DAYS - 1, -1, -1)]
    summaries = []
    drops = []
    for code, product in products.items():
        stores = sorted(product["series"].keys())
        badges: list[str] = []
        latest_prices: list[float] = []
        for store in stores:
            series = product["series"][store]
            if not series:
                continue
            latest_price, latest_promo = series[-1][1], series[-1][2]
            latest_prices.append(latest_price)
            carried = carried_forward_values(series, window_dates)
            if len(carried) < 2:
                continue
            med = statistics.median(carried)
            if med <= 0:
                continue
            if latest_promo and latest_price >= med:
                badges.append(f"fake:{store}")
            if latest_price == min(carried) and latest_price <= med * 0.9:
                pct = (1 - latest_price / med) * 100
                badges.append(f"drop:{store}")
                drops.append({
                    "code": code, "name": product["name"], "store": store,
                    "latest": latest_price, "median": round(med, 2), "pct": round(pct, 1),
                    "date": series[-1][0],  # date the current (low) price took effect
                })
        summaries.append({
            "code": code,
            "brand": product["brand"],
            "name": product["name"],
            "category": product["category"],
            "stores": stores,
            "latest_price_range": [min(latest_prices), max(latest_prices)] if latest_prices else None,
            "badges": badges,
            "last_seen": product["last_seen"],
        })
    summaries.sort(key=lambda s: s["name"])
    drops.sort(key=lambda d: -d["pct"])
    meta = {**state["meta"], "generated_at": today.isoformat()}
    return {"meta": meta, "products": summaries, "drops": drops[:50]}


def load_state() -> dict:
    if not STATE_JSON.exists():
        return {
            "meta": {
                "window_start": None,
                "window_end": None,
                "snapshot_count": 0,
                "source": RESOURCE_URL,
            },
            "products": {},
        }
    try:
        return json.loads(STATE_JSON.read_text())
    except json.JSONDecodeError as exc:
        # Proceeding with an empty state and letting CI commit it would wipe
        # all price history — a hard fail is the safe mode here.
        print(f"products.json corrupt ({exc}) — restore from git", file=sys.stderr)
        sys.exit(1)


def atomic_write_text(path: Path, text: str) -> None:
    """Write via a temp file + os.replace so a killed mid-write run never
    leaves a truncated/corrupt file behind for the next run to trip over."""
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(text)
    os.replace(tmp, path)


def save_state(state: dict) -> None:
    atomic_write_text(STATE_JSON, json.dumps(state, ensure_ascii=False))


def merge_day(state: dict, iso: str, rows: list[dict]) -> None:
    """Apply one day's normalized rows to state["products"], appending a
    sparse point per store only when price/promo changed (plus creating the
    product entry on first sight). Sets last_seen=iso for every product code
    seen today, regardless of whether its series changed."""
    products = state["products"]
    by_code: dict[str, list[dict]] = {}
    for row in rows:
        by_code.setdefault(row["code"], []).append(row)

    for code, code_rows in by_code.items():
        product = products.get(code)
        if product is None:
            first = code_rows[0]
            product = {
                "code": code, "brand": first["brand"], "name": first["name"],
                "category": first["category"], "series": {},
            }
            products[code] = product
        for row in code_rows:
            series = product["series"].setdefault(row["store"], [])
            if not series or series[-1][1] != row["price"] or series[-1][2] != row["offer"]:
                series.append([iso, row["price"], row["offer"]])
        product["last_seen"] = iso


def do_fetch(start: date, end: date) -> None:
    """Populate raw/ with any missing daily snapshots in [start, end]
    (resumable — skips days already cached). Does not touch products.json;
    run --rebuild afterward."""
    RAW_DIR.mkdir(exist_ok=True)
    today = date.today()
    end = min(end, today)
    archive_end = min(end, today - timedelta(days=1))

    per_day: dict[str, str] = {}
    if start <= archive_end:
        print(f"Listing archive versions {start} .. {archive_end} ...")
        try:
            timestamps = list_versions_chunked(start, archive_end)
        except (urllib.error.URLError, OSError, json.JSONDecodeError) as exc:
            print(f"  list-file-versions failed: {exc}", file=sys.stderr)
            timestamps = []
        per_day = one_timestamp_per_day(timestamps)
        print(f"  {len(per_day)} historical days available")

    days: list[tuple[str, str | None]] = [
        (f"{d[:4]}-{d[4:6]}-{d[6:]}", ts) for d, ts in sorted(per_day.items())
    ]
    if end >= today:
        days.append((today.isoformat(), None))

    fetched = skipped = failed = 0
    for iso, ts in days:
        if date.fromisoformat(iso) < start:
            continue
        if (RAW_DIR / f"{iso}.csv").exists():
            skipped += 1
            continue
        print(f"  fetching {iso}")
        if fetch_and_cache_day(iso, ts, use_cache=True) is None:
            failed += 1
        else:
            fetched += 1
        time.sleep(SLEEP_SECS)

    print(f"Fetch done: {fetched} fetched, {skipped} already cached, {failed} failed")


def do_rebuild() -> None:
    """Regenerate products.json from every CSV in raw/."""
    csv_paths = sorted(RAW_DIR.glob("*.csv"))
    products: dict[str, dict] = {}
    for i, csv_path in enumerate(csv_paths):
        iso = csv_path.stem
        rows = normalize_rows(parse_csv_bytes(csv_path.read_bytes()))
        for row in rows:
            code = row["code"]
            product = products.get(code)
            if product is None:
                product = {
                    "code": code, "brand": row["brand"], "name": row["name"],
                    "category": row["category"], "series": {},
                }
                products[code] = product
            series = product["series"].setdefault(row["store"], [])
            if not series or series[-1][1] != row["price"] or series[-1][2] != row["offer"]:
                series.append([iso, row["price"], row["offer"]])
            product["last_seen"] = iso
        if (i + 1) % 200 == 0:
            print(f"  processed {i + 1}/{len(csv_paths)} snapshots")

    meta = {
        "window_start": csv_paths[0].stem if csv_paths else None,
        "window_end": csv_paths[-1].stem if csv_paths else None,
        "snapshot_count": len(csv_paths),
        "source": RESOURCE_URL,
    }
    save_state({"meta": meta, "products": products})
    print(f"Rebuilt {len(products)} products from {len(csv_paths)} snapshots")


def _sampled_days(per_day: dict[str, str]) -> list[tuple[str, str]]:
    """per_day: {'20200530': '20200530-1403', ...}. Returns sorted
    [(iso_date, ts), ...] picking the first available day of each calendar
    month."""
    seen_months: set[str] = set()
    picked: list[tuple[str, str]] = []
    for d in sorted(per_day.keys()):
        if d[:6] not in seen_months:
            seen_months.add(d[:6])
            picked.append((f"{d[:4]}-{d[4:6]}-{d[6:]}", per_day[d]))
    return picked


def _nearest_ts(per_day: dict[str, str], ymd: str) -> str | None:
    """ts for ymd ('20260101'), or the nearest earlier available day's ts if
    the archive has no version that exact day."""
    if ymd in per_day:
        return per_day[ymd]
    earlier = [d for d in per_day if d < ymd]
    return per_day[max(earlier)] if earlier else None


def do_build_names_tc() -> None:
    """One-time build of names_tc.json by monthly-sampling the TC archive
    CSV, then a targeted gap-fill pass: for any product code still missing
    (discontinued between monthly samples), fetch the TC archive for its
    last_seen date specifically — cheap and exact, unlike a blanket weekly
    re-sample of the whole history."""
    state = load_state()
    products = state["products"]
    all_codes = set(products.keys())
    if not all_codes:
        print("products.json has no products — run --rebuild first", file=sys.stderr)
        sys.exit(1)

    yesterday = date.today() - timedelta(days=1)
    print(f"Listing TC archive versions {NAMES_TC_START} .. {yesterday} ...")
    timestamps = list_versions_chunked(NAMES_TC_START, yesterday, RESOURCE_URL_TC)
    per_day = one_timestamp_per_day(timestamps)
    print(f"  {len(per_day)} historical TC days available")

    sampled = _sampled_days(per_day)
    print(f"Sampling monthly: {len(sampled)} archive files + live CSV")
    names: dict[str, dict] = {}
    for i, (iso, ts) in enumerate(sampled):
        raw = fetch_tc_at(ts)
        if raw is not None:
            names.update(extract_names_tc(raw))  # later files win
        time.sleep(SLEEP_SECS)
        if (i + 1) % 20 == 0:
            print(f"  processed {i + 1}/{len(sampled)}")
    raw = fetch_tc_at(None)
    if raw is not None:
        names.update(extract_names_tc(raw))
    print(f"  monthly-sample coverage: {sum(1 for c in all_codes if c in names) / len(all_codes):.1%}")

    missing = [c for c in all_codes if c not in names]
    if missing:
        dates_needed = sorted({
            products[c]["last_seen"] for c in missing if products[c].get("last_seen")
        })
        fetches = 0
        for iso in dates_needed:
            ts = _nearest_ts(per_day, iso.replace("-", ""))
            if ts is None:
                continue
            raw = fetch_tc_at(ts)
            fetches += 1
            time.sleep(SLEEP_SECS)
            if raw is None:
                continue
            for code, entry in extract_names_tc(raw).items():
                names.setdefault(code, entry)  # only fill gaps, never overwrite
        print(f"  gap-fill: {fetches} extra fetch(es) for {len(missing)} missing code(s)")

    still_missing = [c for c in all_codes if c not in names]
    coverage = 1 - len(still_missing) / len(all_codes)
    atomic_write_text(NAMES_TC_JSON, json.dumps(names, ensure_ascii=False, separators=(",", ":")))
    print(f"Wrote {NAMES_TC_JSON} ({len(names)} entries, final coverage {coverage:.1%})")
    if still_missing:
        target_note = "" if coverage >= NAMES_TC_COVERAGE_TARGET else " (below target)"
        print(f"  unresolved{target_note}: {still_missing}")


def update_names_tc(latest_iso: str) -> None:
    """Fetch the TC archive file for latest_iso only and merge new/changed
    codes into names_tc.json (load-if-exists, update, write). Cheap daily
    freshness path — called from --update, unlike --build-names-tc's full
    historical sample."""
    if latest_iso == date.today().isoformat():
        raw = fetch_tc_at(None)
    else:
        d = date.fromisoformat(latest_iso)
        try:
            per_day = one_timestamp_per_day(list_versions(d, d, RESOURCE_URL_TC))
        except (urllib.error.URLError, OSError, json.JSONDecodeError) as exc:
            print(f"  TC list-file-versions failed: {exc}", file=sys.stderr)
            return
        ts = per_day.get(d.strftime("%Y%m%d"))
        raw = fetch_tc_at(ts) if ts else None
    if raw is None:
        print("  TC names update skipped (fetch failed)", file=sys.stderr)
        return
    new_names = extract_names_tc(raw)
    names = json.loads(NAMES_TC_JSON.read_text()) if NAMES_TC_JSON.exists() else {}
    names.update(new_names)
    atomic_write_text(NAMES_TC_JSON, json.dumps(names, ensure_ascii=False, separators=(",", ":")))
    print(f"  TC names updated: {len(new_names)} codes merged")


class PhotoLookupBlocked(Exception):
    """The product-page request itself failed (5xx/timeout/network) —
    unlike a 404 or a 200-with-no-photo, this says nothing about whether the
    product actually has a photo. Callers must not cache it as no-photo;
    the code stays in `todo` and gets retried on a later run."""


class PhotoLookupRateLimited(PhotoLookupBlocked):
    """OPW returned 403 — read as rate-limiting, not "no photo". Raised on
    first sight (no retry: retrying into a 403 only deepens the block).
    Callers should stop the batch, not just skip this one code."""


def fetch_product_photo(code: str) -> str | None:
    """Fetch OPW's product page for code and return the preferred photo path
    (e.g. '/opw/photoRedirect/P000000192/WELLCOME/12'), or None if the page
    confirms no photo for any store in IMAGE_STORE_PREFERENCE (200 response,
    no matching links, or a 404 meaning the product page itself is gone).
    Raises PhotoLookupRateLimited on 403, PhotoLookupBlocked for any other
    fetch failure (retried once first) — see those classes for why neither
    is treated as no-photo."""
    html: str | None = None
    last_exc: Exception | None = None
    for attempt in range(2):
        try:
            raw = fetch_url(
                PRODUCT_PAGE_URL.format(code=code), timeout=20, user_agent=BROWSER_USER_AGENT,
            )
            html = raw.decode("utf-8", errors="replace")
            break
        except urllib.error.HTTPError as exc:
            if exc.code == 404:
                return None
            if exc.code == 403:
                raise PhotoLookupRateLimited(f"{code}: {exc}") from exc
            last_exc = exc
        except (urllib.error.URLError, OSError) as exc:
            last_exc = exc
        time.sleep(IMAGES_REQUEST_SLEEP)
    if html is None:
        raise PhotoLookupBlocked(f"{code}: {last_exc}")

    by_store: dict[str, str] = {}
    for store, photo_id in PHOTO_REDIRECT_RE.findall(html):
        by_store.setdefault(store, photo_id)  # first occurrence = photo idx 1
    for store in IMAGE_STORE_PREFERENCE:
        if store in by_store:
            return f"/opw/photoRedirect/{code}/{store}/{by_store[store]}"
    return None


def _load_images() -> tuple[dict[str, str], dict[str, str]]:
    """images.json -> (code->path map, code->last-checked-date no-photo
    cache). The no-photo cache lives under the reserved NO_PHOTO_KEY so the
    rest of the file stays a flat code->path map for site consumers."""
    if not IMAGES_JSON.exists():
        return {}, {}
    data = json.loads(IMAGES_JSON.read_text())
    return data, data.pop(NO_PHOTO_KEY, {})


def _save_images(images: dict[str, str], no_photo: dict[str, str]) -> None:
    out = {**images, NO_PHOTO_KEY: no_photo}
    atomic_write_text(IMAGES_JSON, json.dumps(out, ensure_ascii=False, separators=(",", ":")))


def _no_photo_fresh(code: str, no_photo: dict[str, str], today: date) -> bool:
    checked = no_photo.get(code)
    return checked is not None and (today - date.fromisoformat(checked)).days < NO_PHOTO_RECHECK_DAYS


def _run_photo_lookups(
    codes: list[str], images: dict[str, str], no_photo: dict[str, str],
) -> tuple[int, int, int]:
    """Look up `codes` with the shared worker pool, updating images/no_photo
    in place. Returns (found, no_photo_count, blocked_count)."""
    today = date.today()
    found = no_photo_count = blocked = 0
    with ThreadPoolExecutor(max_workers=IMAGES_WORKERS) as pool:
        futures = {pool.submit(fetch_product_photo, code): code for code in codes}
        for i, future in enumerate(as_completed(futures)):
            code = futures[future]
            try:
                photo = future.result()
            except PhotoLookupBlocked as exc:
                blocked += 1
                print(f"  blocked: {exc}", file=sys.stderr)
                continue
            if photo:
                images[code] = photo
                found += 1
            else:
                no_photo[code] = today.isoformat()
                no_photo_count += 1
            if (i + 1) % IMAGES_SAVE_EVERY == 0:
                _save_images(images, no_photo)
                print(
                    f"  processed {i + 1}/{len(codes)} ({found} found, "
                    f"{no_photo_count} no-photo, {blocked} blocked)",
                )
    return found, no_photo_count, blocked


def do_build_images() -> None:
    """One-time (local/rare) scrape of one product photo per code into
    images.json. Resumable: codes already resolved (found, or confirmed
    no-photo within NO_PHOTO_RECHECK_DAYS) are skipped; blocked lookups stay
    unresolved so a later run retries them. Saves every IMAGES_SAVE_EVERY
    codes so an interrupted run loses at most that many lookups. Prints
    "DONE all codes attempted" once nothing is left to look up — run this
    repeatedly (with a pause between runs) until that line appears if OPW's
    rate limiting blocks part of a run."""
    state = load_state()
    codes = sorted(state["products"].keys())
    images, no_photo = _load_images()
    today = date.today()
    todo = [c for c in codes if c not in images and not _no_photo_fresh(c, no_photo, today)]
    print(f"{len(codes)} product code(s), {len(todo)} need a photo lookup")
    if not todo:
        print("DONE all codes attempted")
        return

    found, no_photo_count, blocked = _run_photo_lookups(todo, images, no_photo)
    _save_images(images, no_photo)
    print(
        f"Build images done: {len(todo)} attempted, {found} found, {no_photo_count} no-photo, "
        f"{blocked} blocked, {len(images)} total in {IMAGES_JSON}",
    )
    if blocked == 0:
        print("DONE all codes attempted")


def update_images(state: dict) -> None:
    """Top up images.json for up to IMAGES_UPDATE_CAP live codes (last_seen
    == window_end) still unresolved (no photo on file, no fresh no-photo
    check). Called from --update: sequential, one request at a time, and
    stops the whole batch at the first 403 rather than retrying/continuing
    — CI runs this daily, so a small capped batch is enough to eventually
    fill in every live product without ever tripping OPW's rate limit.
    ponytail: cap/pacing tuned from one 403 incident; a full fill this way
    takes ~2 weeks of daily runs — fine, since this only affects images."""
    window_end = state["meta"].get("window_end")
    if window_end is None:
        return
    images, no_photo = _load_images()
    today = date.today()
    live_missing = [
        code for code, product in state["products"].items()
        if product.get("last_seen") == window_end
        and code not in images
        and not _no_photo_fresh(code, no_photo, today)
    ][:IMAGES_UPDATE_CAP]
    if not live_missing:
        return
    print(f"  images: {len(live_missing)} live code(s) missing a photo (capped batch)")

    found = no_photo_count = 0
    for code in live_missing:
        try:
            photo = fetch_product_photo(code)
        except PhotoLookupRateLimited as exc:
            print(f"  images: rate-limited, stopping batch early: {exc}", file=sys.stderr)
            break
        except PhotoLookupBlocked:
            continue
        if photo:
            images[code] = photo
            found += 1
        else:
            no_photo[code] = today.isoformat()
            no_photo_count += 1
        time.sleep(IMAGES_REQUEST_SLEEP)

    _save_images(images, no_photo)
    print(f"  images updated: {found} new photo(s), {no_photo_count} confirmed no-photo")


def do_update() -> None:
    RAW_DIR.mkdir(exist_ok=True)
    today = date.today()

    state = load_state()
    meta = state["meta"]
    window_end_prev = meta.get("window_end")

    # ponytail: first-ever --update run (no products.json) only picks up
    # today — bootstrapping full history is --fetch/--rebuild's job, run once.
    start = date.fromisoformat(window_end_prev) + timedelta(days=1) if window_end_prev else today
    start = min(start, today)
    archive_end = today - timedelta(days=1)

    days: list[tuple[str, str | None]] = []
    if start <= archive_end:
        try:
            timestamps = list_versions_chunked(start, archive_end)
            per_day = one_timestamp_per_day(timestamps)
            days = [(f"{d[:4]}-{d[4:6]}-{d[6:]}", ts) for d, ts in sorted(per_day.items())]
        except (urllib.error.URLError, OSError, json.JSONDecodeError) as exc:
            print(f"  list-file-versions failed, continuing with today only: {exc}", file=sys.stderr)
    days = [(iso, ts) for iso, ts in days if date.fromisoformat(iso) >= start]
    if today.isoformat() not in {iso for iso, _ in days}:
        days.append((today.isoformat(), None))

    latest_merged: str | None = None
    for iso, ts in days:
        rows = fetch_and_cache_day(iso, ts, use_cache=False)
        if rows is None:
            continue
        merge_day(state, iso, rows)
        latest_merged = iso
        if window_end_prev is None or iso > window_end_prev:
            meta["snapshot_count"] += 1
            meta["window_end"] = iso
            meta["window_start"] = meta["window_start"] or iso
            window_end_prev = iso

    save_state(state)
    print(f"Update done: {len(days)} day(s) attempted")

    if latest_merged:
        update_names_tc(latest_merged)

    update_images(state)


def do_export(out_dir: Path) -> None:
    """Regenerate products/<code>.json + index.json (deploy-time site
    artifacts) from products.json into out_dir. Nothing under out_dir is
    committed to git — CI runs this into dist/ before the Pages upload."""
    state = load_state()
    products = state["products"]

    products_dir = out_dir / "products"
    products_dir.mkdir(parents=True, exist_ok=True)
    for code, product in products.items():
        shard = {k: v for k, v in product.items() if k != "last_seen"}
        (products_dir / f"{code}.json").write_text(json.dumps(shard, ensure_ascii=False))

    encoded = json.dumps(build_index(state), ensure_ascii=False)
    (out_dir / "index.json").write_text(encoded)
    print(f"Exported {len(products)} products + index.json ({len(encoded)/1e6:.2f}MB) to {out_dir}")

    if NAMES_TC_JSON.exists():
        (out_dir / "names_tc.json").write_text(NAMES_TC_JSON.read_text())
        print(f"Copied {NAMES_TC_JSON.name} to {out_dir}")

    if IMAGES_JSON.exists():
        (out_dir / "images.json").write_text(IMAGES_JSON.read_text())
        print(f"Copied {IMAGES_JSON.name} to {out_dir}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--fetch", action="store_true", help="download missing raw/ snapshots")
    parser.add_argument("--start", type=str, default="2020-05-30", help="--fetch start date (YYYY-MM-DD)")
    parser.add_argument("--end", type=str, default=None, help="--fetch end date, default today")
    parser.add_argument("--rebuild", action="store_true", help="rebuild products.json from raw/")
    parser.add_argument("--update", action="store_true", help="CI daily incremental update")
    parser.add_argument(
        "--export-site", type=str, default=None, metavar="DIR",
        help="write products/*.json + index.json (deploy artifacts) to DIR",
    )
    parser.add_argument(
        "--build-names-tc", action="store_true",
        help="one-time: build names_tc.json by sampling the TC archive CSV",
    )
    parser.add_argument(
        "--build-images", action="store_true",
        help="one-time: scrape one product photo path per code into images.json",
    )
    args = parser.parse_args()

    if args.update:
        do_update()
    elif args.rebuild:
        do_rebuild()
    elif args.fetch:
        end = date.fromisoformat(args.end) if args.end else date.today()
        do_fetch(date.fromisoformat(args.start), end)
    elif args.export_site:
        do_export(Path(args.export_site))
    elif args.build_names_tc:
        do_build_names_tc()
    elif args.build_images:
        do_build_images()
    else:
        parser.error(
            "pass one of --fetch, --rebuild, --update, --export-site, "
            "--build-names-tc, --build-images",
        )


if __name__ == "__main__":
    main()
