#!/usr/bin/env python3
"""Backfill HK grocery price history from Consumer Council Online Price Watch.

Four modes, stdlib only:
  --fetch --start YYYY-MM-DD   download missing daily CSV snapshots into raw/
                                (resumable, cache-skip; local/rare — recent
                                raw/ CSVs are plain git, older years live as
                                tar bundles on the GitHub Release
                                `raw-archive` and must be restored first).
  --rebuild                    regenerate products.json from every CSV
                                already cached in raw/ (local/rare, needs the
                                full CSV history restored).
  --update                     CI daily: fetch only the days since the last
                                processed date and merge them into
                                products.json. Never trusts a locally-cached
                                raw/*.csv — always re-fetches over the
                                network for the days it processes. Exits 0
                                even on fetch failure so the site stays
                                deployable.
  --export-site DIR            regenerate products/<code>.json + index.json
                                (deploy-time site artifacts) from
                                products.json into DIR. Run by CI into dist/
                                before the Pages upload; neither
                                products/*.json nor index.json is committed.

Storage:
  products.json          single committed state file — sparse per-store
                          price series plus last_seen per product, keyed by
                          product code.
  products/, index.json  generated by --export-site, never committed
                          (gitignored); index.json holds search/badge/drop
                          summaries built from products.json.
  raw/                    recent daily CSV snapshots as plain git blobs;
                          older years are rolled up into `raw-YYYY.tar.zst`
                          assets on the GitHub Release `raw-archive` to keep
                          the repo small.
"""
from __future__ import annotations

import argparse
import csv
import io
import json
import os
import statistics
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from datetime import date, timedelta
from pathlib import Path

RESOURCE_URL = "https://online-price-watch.consumer.org.hk/opw/opendata/pricewatch_en.csv"
LIST_VERSIONS_URL = "https://api.data.gov.hk/v1/historical-archive/list-file-versions"
GET_FILE_URL = "https://api.data.gov.hk/v1/historical-archive/get-file"
ROOT = Path(__file__).parent
RAW_DIR = ROOT / "raw"
STATE_JSON = ROOT / "products.json"
SLEEP_SECS = 0.3
WINDOW_DAYS = 90  # for "biggest drop" / "fake discount" badges

# Pre-2020-07-29 snapshots use a wide schema: one Price/Offers column pair
# per store instead of long-format Supermarket Code/Price rows. Maps the
# wide column suffix to the store code used in the long format.
WIDE_STORE_COLUMNS = {
    "Wellcome": "WELLCOME",
    "PARKnSHOP": "PARKNSHOP",
    "Market Place by Jasons": "JASONS",
    "Watsons": "WATSONS",
    "AEON": "AEON",
    "DCH Food Mart": "DCHFOOD",
}


def fetch_url(url: str, timeout: int = 30) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": "hk-grocery-price-history/0.2"})
    with urllib.request.urlopen(req, timeout=timeout) as resp:  # follows redirects
        return resp.read()


def parse_csv_bytes(raw: bytes) -> list[dict]:
    """Parse OPW CSV bytes -> list of raw row dicts (uses csv module, not
    naive split, since fields like product names can contain commas)."""
    text = raw.decode("utf-8-sig")
    return list(csv.DictReader(io.StringIO(text)))


def is_valid_snapshot(rows: list[dict]) -> bool:
    """Guard against caching a 200 response that isn't really the CSV (error
    page, empty body, schema drift) — forever, since a cached raw file is
    never re-fetched by --fetch/--rebuild."""
    if len(rows) < 100:
        return False
    header = rows[0].keys()
    if "Product Code" not in header:
        return False
    return "Price" in header or any(k.startswith("Price (") for k in header)


def to_price(raw: str) -> float | None:
    try:
        return float(raw)
    except ValueError:
        return None


def normalize_rows(raw_rows: list[dict]) -> list[dict]:
    """Raw csv.DictReader rows (either schema) -> flat rows:
    {code, brand, name, category, store, price, offer}."""
    if not raw_rows:
        return []
    header = raw_rows[0].keys()
    normalized: list[dict] = []
    if "Supermarket Code" in header:
        for row in raw_rows:
            code = row.get("Product Code")
            price = to_price(row.get("Price", ""))
            if not code or price is None:
                continue
            category = " / ".join(
                p for p in (row.get("Category 1"), row.get("Category 2"), row.get("Category 3")) if p
            )
            normalized.append({
                "code": code,
                "brand": row.get("Brand", ""),
                "name": row.get("Product Name", ""),
                "category": category,
                "store": row.get("Supermarket Code", ""),
                "price": price,
                "offer": (row.get("Offers") or "").strip() or None,
            })
    else:
        for row in raw_rows:
            code = row.get("Product Code")
            if not code:
                continue
            category = " / ".join(
                p for p in (row.get("Category 1"), row.get("Category 2"), row.get("Category 3")) if p
            )
            for col_name, store_code in WIDE_STORE_COLUMNS.items():
                price = to_price(row.get(f"Price ({col_name})", ""))
                if price is None:
                    continue
                normalized.append({
                    "code": code,
                    "brand": row.get("Brand", ""),
                    "name": row.get("Product Name", ""),
                    "category": category,
                    "store": store_code,
                    "price": price,
                    "offer": (row.get(f"Offers ({col_name})") or "").strip() or None,
                })
    return normalized


def list_versions(start: date, end: date) -> list[str]:
    encoded = urllib.parse.quote(RESOURCE_URL, safe="")
    url = (
        f"{LIST_VERSIONS_URL}?url={encoded}"
        f"&start={start.strftime('%Y%m%d')}&end={end.strftime('%Y%m%d')}"
    )
    body = json.loads(fetch_url(url))
    return body.get("timestamps", [])


def list_versions_chunked(start: date, end: date) -> list[str]:
    """list-file-versions rejects windows over ~1 year; chunk the request."""
    out: list[str] = []
    cur = start
    while cur <= end:
        chunk_end = min(end, cur + timedelta(days=364))
        out.extend(list_versions(cur, chunk_end))
        cur = chunk_end + timedelta(days=1)
    return out


def one_timestamp_per_day(timestamps: list[str]) -> dict[str, str]:
    """timestamps look like '20260601-1403'. Keep the first (earliest) per day."""
    picked: dict[str, str] = {}
    for ts in sorted(timestamps):
        day = ts.split("-")[0]
        if day not in picked:
            picked[day] = ts
    return picked


def fetch_and_cache_day(iso: str, ts: str | None, *, use_cache: bool) -> list[dict] | None:
    """Fetch one day's snapshot (ts=None means "today", live CSV), cache it
    to raw/, return normalized rows. use_cache=True reuses an existing
    raw/<iso>.csv without hitting the network (used by --fetch/--rebuild,
    which run against a full local CSV history); use_cache=False always
    re-fetches over the network (used by --update, which must never trust a
    locally-cached raw file)."""
    cache_path = RAW_DIR / f"{iso}.csv"
    if use_cache and cache_path.exists():
        return normalize_rows(parse_csv_bytes(cache_path.read_bytes()))

    url = RESOURCE_URL if ts is None else (
        f"{GET_FILE_URL}?url={urllib.parse.quote(RESOURCE_URL, safe='')}&time={ts}"
    )
    try:
        raw = fetch_url(url)
        raw_rows = parse_csv_bytes(raw)
    except (urllib.error.URLError, OSError, UnicodeDecodeError, csv.Error) as exc:
        print(f"  skip {iso}: {exc}", file=sys.stderr)
        return None

    if not is_valid_snapshot(raw_rows):
        print(f"  skip {iso}: response failed validation, not caching", file=sys.stderr)
        return None

    cache_path.write_bytes(raw)
    return normalize_rows(raw_rows)


def carried_forward_values(series: list[list], window_dates: list[str]) -> list[float]:
    """series: sorted [[date, price, offer], ...] (sparse: a point only on
    change). window_dates: sorted ISO dates. Returns the price effective on
    each window day (carrying the last known price forward), skipping days
    before the series' first point."""
    values: list[float] = []
    si = 0
    current: float | None = None
    n = len(series)
    for d in window_dates:
        while si < n and series[si][0] <= d:
            current = series[si][1]
            si += 1
        if current is not None:
            values.append(current)
    return values


def build_index(state: dict) -> dict:
    products = state["products"]
    today = date.today()
    window_dates = [(today - timedelta(days=i)).isoformat() for i in range(WINDOW_DAYS - 1, -1, -1)]
    summaries = []
    drops = []
    for code, product in products.items():
        stores = sorted(product["series"].keys())
        badges: list[str] = []
        latest_prices: list[float] = []
        for store in stores:
            series = product["series"][store]
            if not series:
                continue
            latest_price, latest_promo = series[-1][1], series[-1][2]
            latest_prices.append(latest_price)
            carried = carried_forward_values(series, window_dates)
            if len(carried) < 2:
                continue
            med = statistics.median(carried)
            if med <= 0:
                continue
            if latest_promo and latest_price >= med:
                badges.append(f"fake:{store}")
            if latest_price == min(carried) and latest_price <= med * 0.9:
                pct = (1 - latest_price / med) * 100
                badges.append(f"drop:{store}")
                drops.append({
                    "code": code, "name": product["name"], "store": store,
                    "latest": latest_price, "median": round(med, 2), "pct": round(pct, 1),
                })
        summaries.append({
            "code": code,
            "brand": product["brand"],
            "name": product["name"],
            "category": product["category"],
            "stores": stores,
            "latest_price_range": [min(latest_prices), max(latest_prices)] if latest_prices else None,
            "badges": badges,
            "last_seen": product["last_seen"],
        })
    summaries.sort(key=lambda s: s["name"])
    drops.sort(key=lambda d: -d["pct"])
    meta = {**state["meta"], "generated_at": today.isoformat()}
    return {"meta": meta, "products": summaries, "drops": drops[:50]}


def load_state() -> dict:
    if not STATE_JSON.exists():
        return {
            "meta": {
                "window_start": None,
                "window_end": None,
                "snapshot_count": 0,
                "source": RESOURCE_URL,
            },
            "products": {},
        }
    try:
        return json.loads(STATE_JSON.read_text())
    except json.JSONDecodeError as exc:
        # Proceeding with an empty state and letting CI commit it would wipe
        # all price history — a hard fail is the safe mode here.
        print(f"products.json corrupt ({exc}) — restore from git", file=sys.stderr)
        sys.exit(1)


def atomic_write_text(path: Path, text: str) -> None:
    """Write via a temp file + os.replace so a killed mid-write run never
    leaves a truncated/corrupt file behind for the next run to trip over."""
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(text)
    os.replace(tmp, path)


def save_state(state: dict) -> None:
    atomic_write_text(STATE_JSON, json.dumps(state, ensure_ascii=False))


def merge_day(state: dict, iso: str, rows: list[dict]) -> None:
    """Apply one day's normalized rows to state["products"], appending a
    sparse point per store only when price/promo changed (plus creating the
    product entry on first sight). Sets last_seen=iso for every product code
    seen today, regardless of whether its series changed."""
    products = state["products"]
    by_code: dict[str, list[dict]] = {}
    for row in rows:
        by_code.setdefault(row["code"], []).append(row)

    for code, code_rows in by_code.items():
        product = products.get(code)
        if product is None:
            first = code_rows[0]
            product = {
                "code": code, "brand": first["brand"], "name": first["name"],
                "category": first["category"], "series": {},
            }
            products[code] = product
        for row in code_rows:
            series = product["series"].setdefault(row["store"], [])
            if not series or series[-1][1] != row["price"] or series[-1][2] != row["offer"]:
                series.append([iso, row["price"], row["offer"]])
        product["last_seen"] = iso


def do_fetch(start: date, end: date) -> None:
    """Populate raw/ with any missing daily snapshots in [start, end]
    (resumable — skips days already cached). Does not touch products.json;
    run --rebuild afterward."""
    RAW_DIR.mkdir(exist_ok=True)
    today = date.today()
    end = min(end, today)
    archive_end = min(end, today - timedelta(days=1))

    per_day: dict[str, str] = {}
    if start <= archive_end:
        print(f"Listing archive versions {start} .. {archive_end} ...")
        try:
            timestamps = list_versions_chunked(start, archive_end)
        except (urllib.error.URLError, OSError, json.JSONDecodeError) as exc:
            print(f"  list-file-versions failed: {exc}", file=sys.stderr)
            timestamps = []
        per_day = one_timestamp_per_day(timestamps)
        print(f"  {len(per_day)} historical days available")

    days: list[tuple[str, str | None]] = [
        (f"{d[:4]}-{d[4:6]}-{d[6:]}", ts) for d, ts in sorted(per_day.items())
    ]
    if end >= today:
        days.append((today.isoformat(), None))

    fetched = skipped = failed = 0
    for iso, ts in days:
        if date.fromisoformat(iso) < start:
            continue
        if (RAW_DIR / f"{iso}.csv").exists():
            skipped += 1
            continue
        print(f"  fetching {iso}")
        if fetch_and_cache_day(iso, ts, use_cache=True) is None:
            failed += 1
        else:
            fetched += 1
        time.sleep(SLEEP_SECS)

    print(f"Fetch done: {fetched} fetched, {skipped} already cached, {failed} failed")


def do_rebuild() -> None:
    """Regenerate products.json from every CSV in raw/."""
    csv_paths = sorted(RAW_DIR.glob("*.csv"))
    products: dict[str, dict] = {}
    for i, csv_path in enumerate(csv_paths):
        iso = csv_path.stem
        rows = normalize_rows(parse_csv_bytes(csv_path.read_bytes()))
        for row in rows:
            code = row["code"]
            product = products.get(code)
            if product is None:
                product = {
                    "code": code, "brand": row["brand"], "name": row["name"],
                    "category": row["category"], "series": {},
                }
                products[code] = product
            series = product["series"].setdefault(row["store"], [])
            if not series or series[-1][1] != row["price"] or series[-1][2] != row["offer"]:
                series.append([iso, row["price"], row["offer"]])
            product["last_seen"] = iso
        if (i + 1) % 200 == 0:
            print(f"  processed {i + 1}/{len(csv_paths)} snapshots")

    meta = {
        "window_start": csv_paths[0].stem if csv_paths else None,
        "window_end": csv_paths[-1].stem if csv_paths else None,
        "snapshot_count": len(csv_paths),
        "source": RESOURCE_URL,
    }
    save_state({"meta": meta, "products": products})
    print(f"Rebuilt {len(products)} products from {len(csv_paths)} snapshots")


def do_update() -> None:
    RAW_DIR.mkdir(exist_ok=True)
    today = date.today()

    state = load_state()
    meta = state["meta"]
    window_end_prev = meta.get("window_end")

    # ponytail: first-ever --update run (no products.json) only picks up
    # today — bootstrapping full history is --fetch/--rebuild's job, run once.
    start = date.fromisoformat(window_end_prev) + timedelta(days=1) if window_end_prev else today
    start = min(start, today)
    archive_end = today - timedelta(days=1)

    days: list[tuple[str, str | None]] = []
    if start <= archive_end:
        try:
            timestamps = list_versions_chunked(start, archive_end)
            per_day = one_timestamp_per_day(timestamps)
            days = [(f"{d[:4]}-{d[4:6]}-{d[6:]}", ts) for d, ts in sorted(per_day.items())]
        except (urllib.error.URLError, OSError, json.JSONDecodeError) as exc:
            print(f"  list-file-versions failed, continuing with today only: {exc}", file=sys.stderr)
    days = [(iso, ts) for iso, ts in days if date.fromisoformat(iso) >= start]
    if today.isoformat() not in {iso for iso, _ in days}:
        days.append((today.isoformat(), None))

    for iso, ts in days:
        rows = fetch_and_cache_day(iso, ts, use_cache=False)
        if rows is None:
            continue
        merge_day(state, iso, rows)
        if window_end_prev is None or iso > window_end_prev:
            meta["snapshot_count"] += 1
            meta["window_end"] = iso
            meta["window_start"] = meta["window_start"] or iso
            window_end_prev = iso

    save_state(state)
    print(f"Update done: {len(days)} day(s) attempted")


def do_export(out_dir: Path) -> None:
    """Regenerate products/<code>.json + index.json (deploy-time site
    artifacts) from products.json into out_dir. Nothing under out_dir is
    committed to git — CI runs this into dist/ before the Pages upload."""
    state = load_state()
    products = state["products"]

    products_dir = out_dir / "products"
    products_dir.mkdir(parents=True, exist_ok=True)
    for code, product in products.items():
        shard = {k: v for k, v in product.items() if k != "last_seen"}
        (products_dir / f"{code}.json").write_text(json.dumps(shard, ensure_ascii=False))

    encoded = json.dumps(build_index(state), ensure_ascii=False)
    (out_dir / "index.json").write_text(encoded)
    print(f"Exported {len(products)} products + index.json ({len(encoded)/1e6:.2f}MB) to {out_dir}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--fetch", action="store_true", help="download missing raw/ snapshots")
    parser.add_argument("--start", type=str, default="2020-05-30", help="--fetch start date (YYYY-MM-DD)")
    parser.add_argument("--end", type=str, default=None, help="--fetch end date, default today")
    parser.add_argument("--rebuild", action="store_true", help="rebuild products.json from raw/")
    parser.add_argument("--update", action="store_true", help="CI daily incremental update")
    parser.add_argument(
        "--export-site", type=str, default=None, metavar="DIR",
        help="write products/*.json + index.json (deploy artifacts) to DIR",
    )
    args = parser.parse_args()

    if args.update:
        do_update()
    elif args.rebuild:
        do_rebuild()
    elif args.fetch:
        end = date.fromisoformat(args.end) if args.end else date.today()
        do_fetch(date.fromisoformat(args.start), end)
    elif args.export_site:
        do_export(Path(args.export_site))
    else:
        parser.error("pass one of --fetch, --rebuild, --update, --export-site")


if __name__ == "__main__":
    main()
